### PR TITLE
Fixed a few bugs

### PR DESCRIPTION
**Pull request by arjunmahishi**
There are no breaking changes

### CODE REVIEW

**Comment by ionicc** [comment]
Thanks for the contribution @arjunmahishi 😄 
Could you attach some screenshots of the changes so we can inspect them more properly.

**Comment by arjunmahishi** [comment]
Sure...

### Footer gap fix
old footer
|---------------------|

new footer
|---------------------|

### Console errors
old console
|---------------------|

### Cards
Old cards
|---------------------|

new cards
|---------------------|

**Comment by ionicc** [comment]
Alright great work 🛩

**Comment by ionicc** [comment]
@Aniket-Mishra Could you review this?

**Pull request merged**
